### ISSUE TITLE
The official solution for Expressworks WHAT'S IN QUERY - Does not work.

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [reddock/fcc_express#1]
The official solution for Expressworks WHAT'S IN QUERY:

var express = require('express')
var app = express()

app.get('/search', function(req, res){
  var query = req.query
  res.send(query)
})

app.listen(process.argv[2])
Gives:

```
         ACTUAL                                 EXPECTED                
```

───────────────────────────────────────────────────

"{" != "{\"results\":\"recent\",\"type\":\"quote\",\"page\":\"8\"}"
" \"type\": \"quote\"," !=

" \"page\": \"8\"," !=

" \"proto\": {}" !=

"}" !=

It is obviously not expecting: " \"proto\": {}"

Manually building the object like so does work:

app.get('/search', function(req, res){
var send = {};
send.results = req.query.results;
send.type = req.query.type;
send.page = req.query.page;

send = JSON.stringify(send);
res.status(200).send(send);
});

**Comment by prashcr** [comment]
This is the wrong place to post though. This repo is just for config files to set up expressworks to work with c9. 
Here's the actual repo
https://github.com/azat-co/expressworks
Actually, post it both here and there, since they use specific versions in these config files that might also be causing the issue
